### PR TITLE
Issue #101: Notifier: The test for mailto should be case insensitive.

### PR DESCRIPTION
**Pull request by ggallen**

### CODE REVIEW

**Comment by ggallen** [comment]
I have updated this pull request to include code that passes recipients (from the subscription) to applyTemplates where they can then be placed into the template environment for use in the templates.

I realized this was needed as the invite-reply notifications do not contain who the notification is going to.

**Comment by ggallen** [comment]
Mike, I just committed my code to include the JSON event in the template environment. I have this working with my templates and it looks great.  I'm sure there will be some more work here as I get to the updated and deleted events, but I wanted to get this checked in as these other changes are likely to be minor when I get to them.

I also moved the applyTemplates method into the EmailAdaptor itself. In my opinion it was becoming to email-centric to leave in the AbstractAdaptor class.  And I'm not sure templates would even make sense for another adapter type - maybe, or maybe not.

-- Greg

**Comment by douglm** [comment]
On 2/24/16 20:45, ggallen wrote:

> Mike, I just committed my code to include the JSON event in the template
> environment. I have this working with my templates and it looks great.
> I'm sure there will be some more work here as I get to the updated and
> deleted events, but I wanted to get this checked in as these other
> changes are likely to be minor when I get to them.
> 
> I also moved the applyTemplates method into the EmailAdaptor itself. In
> my opinion it was becoming to email-centric to leave in the
> AbstractAdaptor class. And I'm not sure templates would even make sense
> for another adapter type - maybe, or maybe not.

FreeMarker is used for generating all sorts of stuff - including html. 
Some products use it instead of jsp so it really should be usable for 
anything that needs a formatter.

I'm not sure why it couldn't be used for text messages for example.

**Comment by ggallen** [comment]
Yes, I agree it could. But a text message is much shorter than an email would be, and I think that all the data I was putting into the env for the templates for email would be wasted on a text.

But I can change it back if you want.

**Comment by douglm** [comment]
Even for sms you probably want some directory and some event info

**Comment by ggallen** [comment]
Mike,

There is one other reason I moved this stuff to the EmailAdaptor class.

For resource-change notifications, we want to call back the the server to get the JSON iCal event and put that in the environment for the templates. All this connection information is already available in BedeworkConnection which can be retrieved from the Action. However, when I made these changes in the AbstractAdaptor class, I also add to add a dependency in the pom.xml for bw-note-bwconnector. This causes a cycle.

You can see what I am talking about in the EmailAdaptor.applyTemplates method, starting around line #284.

Do you have a suggestion for me here?

**Comment by douglm** [comment]
Let's just leave it as it is for now.

**Pull request merged**
